{{- if and .Values.opensearch.enabled .Values.fluentBit.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stack.fullname" . }}-opensearch-index-template
  labels:
    {{- include "stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch
data:
  template.json: |
    {
      "index_patterns": ["kubernetes-logs-*"],
      "template": {
        "mappings": {
          "properties": {
            "log_processed": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "text",
                  "fields": { "keyword": { "type": "keyword" } }
                },
                "traceId": { "type": "keyword" },
                "spanId": { "type": "keyword" },
                "level": { "type": "keyword" },
                "logger_name": { "type": "keyword" },
                "appName": { "type": "keyword" },
                "@timestamp": { "type": "date" },
                "thread_name": { "type": "keyword" },
                "level_value": { "type": "integer" },
                "@version": { "type": "keyword" }
              }
            }
          }
        }
      }
    }
{{- end }}
