{{- if and .Values.opensearch.enabled (not .Values.opensearch.disableSecurity) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stack.fullname" . }}-opensearch
  labels:
    {{- include "stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch
type: Opaque
stringData:
  admin-password: {{ .Values.opensearch.adminPassword | quote }}
{{- end }}
