{{- if .Values.tempo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stack.fullname" . }}-tempo
  labels:
    {{- include "stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  type: {{ .Values.tempo.service.type }}
  ports:
  - port: {{ .Values.tempo.service.ports.http }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.tempo.service.ports.otlpGrpc }}
    targetPort: otlp-grpc
    protocol: TCP
    name: otlp-grpc
  - port: {{ .Values.tempo.service.ports.otlpHttp }}
    targetPort: otlp-http
    protocol: TCP
    name: otlp-http
  selector:
    {{- include "stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
{{- end }}
