{{- if and .Values.postgresql.enabled .Values.postgresql.backup .Values.postgresql.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stack.fullname" . }}-postgresql-backup
  labels:
    {{- include "stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.backup.pvc.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
