{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stack.fullname" . }}-prometheus-config
  labels:
    {{- include "stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
{{- $promConfig := .Files.Get "config/prometheus.yml" }}
{{- $appJob := "- job_name: 'service-app'" }}
{{- if .Values.application.enabled }}
{{- $appTarget := printf "%s-app:8082" (include "stack.fullname" .) }}
{{ $promConfig | replace "__APP_TARGET__" $appTarget | nindent 4 }}
{{- else }}
{{- $parts := split $appJob $promConfig }}
{{ (index $parts "_0") | trimSuffix "\n" | nindent 4 }}
{{- end }}
{{- end }}
