{{- if and .Values.application.enabled .Values.application.autoscaling .Values.application.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stack.fullname" . }}-app
  labels:
    {{- include "stack.labels" . | nindent 4 }}
spec:
  maxUnavailable: "25%"
  selector:
    matchLabels:
      {{- include "stack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
