{{- if and .Values.opensearch.enabled .Values.opensearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stack.fullname" . }}-opensearch
  labels:
    {{- include "stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.opensearch.persistence.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
